[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.7.0-rc", features = ["csr", "tracing"] }
leptos_devtools = { path = "../devtools" }
tracing-subscriber = "0.3.18"