[package]
name = "leptos_devtools_extension_api"
version = { workspace = true }
edition = "2021"
authors = ["luoxiaozero"]
description = "leptos_devtools extension api"
repository = "https://github.com/luoxiaozero/leptos-devtools"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive"] }
wasm-bindgen.workspace = true
serde-wasm-bindgen = "0.6.0"
js-sys = "0.3.64"

[dependencies.web-sys]
version = "0.3.64"
features = ["console", "Window", "MessageEvent"]

[dev-dependencies]
serde_json = "1.0.107"
