[package]
publish = false
name = "extension_devtools"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrome-wasm-bindgen = { git = "https://github.com/luoxiaozero/chrome-wasm-bindgen.git" }